"""Stock screening strategy layer."""

from gupiao.strategies.screening import (
    AuctionGapReversalShortStrategy,
    AuctionOpenBreakoutShortStrategy,
    LowVolatilityBreakoutStrategy,
    MomentumPullbackStrategy,
    MovingAverageVolumeBreakoutStrategy,
    ScreeningCandidate,
    ScreeningStrategy,
    StrategySpec,
    TrendQualityMidStrategy,
    available_strategy_specs,
    build_screening_strategy,
    get_strategy_spec,
    score_candidate,
    score_with_auction,
)
from gupiao.strategies.morning import (
    MorningScreenConfig,
    MorningScreenResult,
    MorningScreenRow,
    auction_profile_for_trade_date,
    daily_bars_visible_before_decision,
    run_morning_screen,
)
from gupiao.strategies.selection import (
    CandidateScreenConfig,
    CandidateScreenResult,
    CandidateScreenRow,
    bars_up_to,
    run_cached_candidate_screen,
)

__all__ = [
    "AuctionGapReversalShortStrategy",
    "AuctionOpenBreakoutShortStrategy",
    "CandidateScreenConfig",
    "CandidateScreenResult",
    "CandidateScreenRow",
    "LowVolatilityBreakoutStrategy",
    "MomentumPullbackStrategy",
    "MovingAverageVolumeBreakoutStrategy",
    "MorningScreenConfig",
    "MorningScreenResult",
    "MorningScreenRow",
    "ScreeningCandidate",
    "ScreeningStrategy",
    "StrategySpec",
    "TrendQualityMidStrategy",
    "auction_profile_for_trade_date",
    "available_strategy_specs",
    "build_screening_strategy",
    "bars_up_to",
    "daily_bars_visible_before_decision",
    "get_strategy_spec",
    "run_morning_screen",
    "run_cached_candidate_screen",
    "score_candidate",
    "score_with_auction",
]
